source 'http://rubygems.org'

gem 'rack-cors', :require => 'rack/cors'
gem 'sass'
gem 'sinatra'
gem 'shotgun'
gem 'pry'
gem 'omniauth-tumblr', :git => 'git://github.com/jamiew/omniauth-tumblr.git'
gem 'omniauth-evernote'
gem 'catapult'
gem 'rest-client'
gem 'json'
gem 'foreman'
